### ISSUE TITLE
Demo app multiple errors during syncing leading to inability to use

### ISSUE THREAD

**Issue by twidtwo** [mollyim/monero-wallet-sdk#1]
Is the demo currently supposed to be in a fully functional state. I was trying to test the functionality using a private monero testnet and got multiple different errors while trying to sync an imported wallet and when trying to scan transactions with a wallet created in the demo. If you are interested I can supply logs and recreation steps but wasn't sure what the current state of the project is.

**Comment by valldrac** [comment]
Thanks for your interest. The SDK is under heavy development, in alpha state. But importing and syncing a wallet should work.

I'd really appreciate if you could share the details to diagnose the issues you mentioned.
